<?php

namespace Xul\AuthKit\Support;

use Illuminate\Contracts\Cache\Repository as CacheRepository;
use Psr\SimpleCache\InvalidArgumentException;
use Xul\AuthKit\Contracts\TokenRepositoryContract;

/**
 * PendingPasswordReset
 *
 * Tracks pending password reset state for an email address.
 *
 * Design:
 * - Creates a single-use reset token in TokenRepository keyed by normalized email.
 * - Stores a short-lived "presence" key keyed by email so UI middleware can confirm
 *   a reset flow exists without knowing the raw token.
 *
 * Driver behavior:
 * - When authkit.password_reset.driver is "link":
 *   - A long token is generated by the TokenRepository (enforced by the repository).
 *   - The token is typically delivered as part of a reset URL.
 * - When authkit.password_reset.driver is "token":
 *   - A user-friendly code/token is generated (shape controlled by authkit.tokens).
 *   - The token is typically delivered for manual entry.
 *
 * Token options:
 * - Token creation options are derived here when driver is "token" from:
 *   - authkit.tokens.types.password_reset
 * - Link driver does not supply options; the repository enforces a long token.
 *
 * Notes:
 * - Link driver typically sends: /reset-password/{token}?email=...
 * - Token driver typically sends a code/token to be entered by the user; the UI may
 *   also accept ?email=... for reset context.
 */
final class PendingPasswordReset
{
    /**
     * Create a new instance.
     *
     * @param TokenRepositoryContract $tokens
     * @param CacheRepository $cache
     */
    public function __construct(
        protected TokenRepositoryContract $tokens,
        protected CacheRepository $cache
    ) {}

    /**
     * Create a pending password reset token for an email.
     *
     * Presence tracking:
     * - A presence key is stored to support UI middleware and multi-step flows.
     *
     * Token generation:
     * - Options are applied only for token-driver flows.
     * - Repository enforces a long token for link-driver flows.
     *
     * @param string $email
     * @param int $ttlMinutes
     * @param array $payload
     *
     * @return string
     */
    public function createForEmail(string $email, int $ttlMinutes, array $payload = []): string
    {
        $emailKey = $this->emailKey($email);

        $this->cache->put(
            $this->presenceKey($emailKey),
            true,
            now()->addMinutes($ttlMinutes)
        );

        $driver = (string) config('authkit.password_reset.driver', 'link');

        $options = $driver === 'token'
            ? (array) config('authkit.tokens.types.password_reset', [])
            : [];

        return $this->tokens->create(
            type: 'password_reset',
            identifier: $emailKey,
            ttlMinutes: $ttlMinutes,
            payload: array_merge([
                'email' => $emailKey,
                'created_at' => now()->toISOString(),
            ], $payload),
            options: $options
        );
    }

    /**
     * Mark an email as having a pending reset flow.
     *
     * Useful for "link" driver UIs where a pending flow should be asserted
     * without creating a new token in that moment.
     *
     * @param string $email
     * @param int $ttlMinutes
     *
     * @return void
     */
    public function markPendingForEmail(string $email, int $ttlMinutes): void
    {
        $emailKey = $this->emailKey($email);

        $this->cache->put(
            $this->presenceKey($emailKey),
            true,
            now()->addMinutes($ttlMinutes)
        );
    }

    /**
     * Determine if an email currently has a pending reset flow.
     *
     * @param string $email
     *
     * @return bool
     * @throws InvalidArgumentException
     */
    public function hasPendingForEmail(string $email): bool
    {
        $emailKey = $this->emailKey($email);

        return (bool) $this->cache->get($this->presenceKey($emailKey), false);
    }

    /**
     * Peek a reset token payload without consuming it.
     *
     * @param string $email
     * @param string $token
     *
     * @return array|null
     * @throws InvalidArgumentException
     */
    public function peekToken(string $email, string $token): ?array
    {
        $emailKey = $this->emailKey($email);

        return $this->tokens->peek(
            type: 'password_reset',
            identifier: $emailKey,
            token: $token
        );
    }

    /**
     * Validate and consume a reset token.
     *
     * If valid, the token is consumed and the presence key is cleared.
     *
     * @param string $email
     * @param string $token
     *
     * @return array|null
     */
    public function consumeToken(string $email, string $token): ?array
    {
        $emailKey = $this->emailKey($email);

        $payload = $this->tokens->validate(
            type: 'password_reset',
            identifier: $emailKey,
            token: $token
        );

        if ($payload) {
            $this->cache->forget($this->presenceKey($emailKey));
        }

        return $payload;
    }

    /**
     * Determine if a reset token is valid for an email without consuming it.
     *
     * @param string $email
     * @param string $token
     *
     * @return bool
     * @throws InvalidArgumentException
     */
    public function isTokenValidForEmail(string $email, string $token): bool
    {
        return $this->peekToken($email, $token) !== null;
    }

    /**
     * Normalize email into a stable identifier.
     *
     * @param string $email
     *
     * @return string
     */
    protected function emailKey(string $email): string
    {
        return mb_strtolower(trim($email));
    }

    /**
     * Build the presence key for a given email identifier.
     *
     * @param string $emailKey
     *
     * @return string
     */
    protected function presenceKey(string $emailKey): string
    {
        return "authkit:password_reset:pending:{$emailKey}";
    }
}