<?php

namespace Xul\AuthKit\Support;

use Psr\SimpleCache\InvalidArgumentException;
use Xul\AuthKit\Contracts\TokenRepositoryContract;

/**
 * PendingLogin
 *
 * Manages pending login challenges used by two-factor authentication flows.
 *
 * A pending login challenge is a short-lived, single-use token that stores the
 * context required to complete authentication after primary credential checks.
 *
 * Storage model:
 * - The raw challenge token is generated by the TokenRepository implementation.
 * - The challenge payload is persisted for a limited TTL.
 * - Consuming the challenge invalidates it immediately (single-use).
 *
 * Token shape:
 * - Pending login challenges are not intended for manual entry.
 * - Token shape is controlled by authkit.tokens configuration for the "pending_login" type.
 */
final class PendingLogin
{
    /**
     * Create a new instance.
     *
     * @param TokenRepositoryContract $tokens
     */
    public function __construct(
        protected TokenRepositoryContract $tokens
    ) {}

    /**
     * Create a pending login challenge.
     *
     * The returned value is the raw challenge token. The payload includes:
     * - user_id: authenticated user identifier
     * - remember: remember-me flag carried into the final session login step
     * - methods: allowed two-factor methods for the challenge
     * - created_at: challenge creation time
     *
     * Token options:
     * - Options are resolved internally by the TokenRepository using:
     *   - authkit.tokens.default
     *   - authkit.tokens.types.pending_login
     *
     * @param string $userId
     * @param bool $remember
     * @param int $ttlMinutes
     * @param array $methods
     *
     * @return string
     */
    public function create(string $userId, bool $remember, int $ttlMinutes, array $methods = ['totp']): string
    {
        return $this->tokens->create(
            type: 'pending_login',
            identifier: 'pending',
            ttlMinutes: $ttlMinutes,
            payload: [
                'user_id' => $userId,
                'remember' => $remember,
                'methods' => array_values($methods),
                'created_at' => now()->toISOString(),
            ],
            options: (array) config('authkit.tokens.types.pending_login', [])
        );
    }

    /**
     * Retrieve a pending login payload without consuming it.
     *
     * This is used by two-factor pages to confirm the existence of a challenge
     * before attempting completion.
     *
     * @param string $challenge
     *
     * @return array|null
     * @throws InvalidArgumentException
     */
    public function peek(string $challenge): ?array
    {
        return $this->tokens->peek(
            type: 'pending_login',
            identifier: 'pending',
            token: $challenge
        );
    }

    /**
     * Consume (retrieve and invalidate) a pending login challenge.
     *
     * On success, the payload is returned and the challenge is invalidated immediately.
     * On failure (invalid or expired), null is returned.
     *
     * @param string $challenge
     *
     * @return array|null
     */
    public function consume(string $challenge): ?array
    {
        return $this->tokens->validate(
            type: 'pending_login',
            identifier: 'pending',
            token: $challenge
        );
    }

    /**
     * Delete a pending login challenge.
     *
     * This removes the token without validating it.
     *
     * @param string $challenge
     *
     * @return void
     */
    public function forget(string $challenge): void
    {
        $this->tokens->delete(
            type: 'pending_login',
            identifier: 'pending',
            token: $challenge
        );
    }
}